version: '3'

volumes:
  pg_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_foodgram:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: carlodipalma/foodgram_backend:latest
    env_file: ../.env
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/app/media
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
#    env_file: ../.env
    image: carlodipalma/foodgram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static_foodgram:/static
  gateway:
    container_name: foodgram-nginx
    image: carlodipalma/foodgram_gateway:latest
#    env_file: ../.env
    ports:
      - 9000:80
    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_foodgram:/static
      - media_foodgram:/app/media
    depends_on:
      - backend
      - frontend