# Generated by Django 3.2.20 on 2023-08-11 10:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(
                default='#F1F1F1',
                image_field=None,
                max_length=18,
                samples=None
            ),
        ),
    ]
