# Generated by Django 3.2.20 on 2023-08-16 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(
                    1,
                    message='Минимум одна минута'
                )]
            ),
        ),
    ]
