# Generated by Django 3.2.20 on 2023-08-16 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='date joined'
            ),
        ),
    ]
