# Generated by Django 3.2.20 on 2023-08-17 18:34

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('author',
                     django.db.models.expressions.F('follower')),
                    _negated=True
                ),
                name='no_self_following'
            ),
        ),
    ]
